name: "CI CD pipeline / workflows"

on:
    push:
         branches:
         - master
         - main   

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: "setup node js"
              uses: actions/setup-node@v4
              with: 
                node-version: '21'
            - name: "clone the repository"
              uses: actions/checkout@v2
            - name: "installing dependencies"
              uses: npm install  

